name: Build and Push Docker Image

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: extractions/setup-just@v2
        with:
          just-version: 1.37.0
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Lint
        run: just lint
      - name: Runs all tests
        run: just test
      # - name: Run chart-testing (lint)
      #   uses: helm/chart-testing-action@main
      #   with:
      #     command: lint
      #     config: .github/ct.yaml

      # - name: Runs helm docs
      #   run: make helm-docs
